# Generated by Django 4.0.4 on 2022-05-27 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_bio_user_password_alter_user_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(editable=False, max_length=64, verbose_name='password hash'),
        ),
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(editable=False, max_length=50, verbose_name='token'),
        ),
    ]
